# Generated by Django 6.0.6 on 2026-07-04 09:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.CharField(max_length=64, verbose_name='شماره چک')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ')),
                ('issuing_bank', models.CharField(max_length=128, verbose_name='بانک صادرکننده')),
                ('status', models.CharField(choices=[('pending', 'وصول\u200cنشده'), ('cleared', 'وصول\u200cشده'), ('bounced', 'برگشتی')], default='pending', max_length=16, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'چک',
                'verbose_name_plural': 'چک\u200cها',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('cash', 'نقدی'), ('installment', 'اقساطی'), ('leasing', 'لیزینگ')], max_length=16, verbose_name='نوع قرارداد')),
                ('signed_date', models.DateField(verbose_name='تاریخ امضا')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ کل (ریال)')),
                ('down_payment', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='مبلغ پیش\u200cپرداخت')),
                ('installments_count', models.PositiveIntegerField(default=0, verbose_name='تعداد اقساط')),
                ('installment_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='مبلغ هر قسط')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'تکمیل\u200cشده'), ('cancelled', 'لغو\u200cشده')], default='active', max_length=16, verbose_name='وضعیت')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='فایل پیوست قرارداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
                'ordering': ['-signed_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='تاریخ برنامه\u200cریزی\u200cشده')),
                ('description', models.CharField(max_length=255, verbose_name='شرح مرحله')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل\u200cشده')),
            ],
            options={
                'verbose_name': 'مرحله تحویل',
                'verbose_name_plural': 'مراحل تحویل',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=32, unique=True, verbose_name='شماره پیش\u200cفاکتور')),
                ('valid_until', models.DateField(verbose_name='تاریخ اعتبار')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='درصد تخفیف')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('9'), max_digits=5, verbose_name='درصد مالیات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پیش\u200cفاکتور',
                'verbose_name_plural': 'پیش\u200cفاکتورها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='شرح')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=16, verbose_name='قیمت واحد (ریال)')),
            ],
            options={
                'verbose_name': 'آیتم پیش\u200cفاکتور',
                'verbose_name_plural': 'آیتم\u200cهای پیش\u200cفاکتور',
            },
        ),
    ]
