# Generated by Django 6.0.6 on 2026-07-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید مشتری'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_confirmed_by_customer',
            field=models.BooleanField(default=False, help_text='وقتی مشتری از پرتال خودش این قرارداد را تایید کند، این فیلد True می\u200cشود.', verbose_name='تایید شده توسط مشتری'),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ مشتری'),
        ),
        migrations.AddField(
            model_name='quote',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال به مشتری'),
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس (هنوز ارسال نشده)'), ('sent', 'ارسال\u200cشده برای مشتری (در انتظار تایید)'), ('approved', 'تایید شده توسط مشتری'), ('rejected', 'رد شده توسط مشتری')], default='draft', max_length=16, verbose_name='وضعیت'),
        ),
    ]
