# Generated by Django 6.0.6 on 2026-07-04 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('individual', 'حقیقی'), ('legal', 'حقوقی')], default='legal', max_length=16, verbose_name='نوع مشتری')),
                ('name', models.CharField(max_length=255, verbose_name='نام / نام شرکت')),
                ('national_or_economic_id', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی/اقتصادی باید بین ۱۰ تا ۱۱ رقم باشد.', regex='^\\d{10,11}$')], verbose_name='کد ملی / کد اقتصادی')),
                ('phone_number', models.CharField(max_length=20, verbose_name='تلفن')),
                ('secondary_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن دوم')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('is_verified', models.BooleanField(default=False, verbose_name='اعتبارسنجی شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call', 'تماس تلفنی'), ('meeting', 'جلسه حضوری'), ('follow_up', 'پیگیری'), ('email', 'ایمیل')], max_length=16, verbose_name='نوع تعامل')),
                ('date', models.DateTimeField(verbose_name='تاریخ')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تعامل',
                'verbose_name_plural': 'تعاملات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalesOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پروژه')),
                ('machine_model', models.CharField(max_length=255, verbose_name='مدل دستگاه')),
                ('estimated_budget', models.DecimalField(decimal_places=0, max_digits=16, verbose_name='بودجه تقریبی (ریال)')),
                ('status', models.CharField(choices=[('serious', 'جدی'), ('negotiation', 'در حال مذاکره'), ('quote_sent', 'ارسال پیش\u200cفاکتور'), ('closed_won', 'بسته\u200cشده (موفق)'), ('cancelled', 'لغو\u200cشده')], default='serious', max_length=16, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'فرصت فروش',
                'verbose_name_plural': 'فرصت\u200cهای فروش',
                'ordering': ['-created_at'],
            },
        ),
    ]
