# Generated by Django 6.0.6 on 2026-07-04 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس فروش مسئول'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='salesopportunity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='customers.customer', verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='salesopportunity',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس مسئول'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customers.salesopportunity', verbose_name='فرصت فروش'),
        ),
    ]
