# Generated by Django 6.0.6 on 2026-07-05 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_salesopportunity_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='portal_user',
            field=models.OneToOneField(blank=True, help_text='در صورت ایجاد، این مشتری می\u200cتواند با این حساب وارد پرتال مشتری شود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_record', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری پرتال مشتری'),
        ),
    ]
