# Generated by Django 6.0.6 on 2026-07-04 09:09

import apps.workshop.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_identifier', models.CharField(max_length=255, verbose_name='شناسه/شاسی دستگاه')),
                ('received_at', models.DateField(auto_now_add=True, verbose_name='تاریخ پذیرش')),
                ('fault_type', models.CharField(max_length=255, verbose_name='نوع خرابی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending_review', 'در انتظار بررسی'), ('in_repair', 'در حال تعمیر'), ('completed', 'تکمیل\u200cشده'), ('delivered', 'تحویل داده\u200cشده')], default='pending_review', max_length=16, verbose_name='وضعیت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'درخواست تعمیر',
                'verbose_name_plural': 'درخواست\u200cهای تعمیر',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.workshop.models.service_request_upload_path, verbose_name='تصویر')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workshop.servicerequest', verbose_name='درخواست تعمیر')),
            ],
            options={
                'verbose_name': 'تصویر درخواست تعمیر',
                'verbose_name_plural': 'تصاویر درخواست تعمیر',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workshop.servicerequest', verbose_name='درخواست تعمیر')),
            ],
            options={
                'verbose_name': 'تخصیص کار',
                'verbose_name_plural': 'تخصیص\u200cهای کار',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('parts_used', models.TextField(blank=True, verbose_name='قطعات مصرفی')),
                ('hours_spent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ساعت صرف\u200cشده')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_logs', to='workshop.taskassignment', verbose_name='تخصیص کار')),
            ],
            options={
                'verbose_name': 'گزارش تعمیر',
                'verbose_name_plural': 'گزارش\u200cهای تعمیر',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=255, verbose_name='تخصص')),
                ('rank', models.CharField(blank=True, max_length=64, verbose_name='رتبه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'تکنسین',
                'verbose_name_plural': 'تکنسین\u200cها',
            },
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workshop.technician', verbose_name='تکنسین'),
        ),
        migrations.CreateModel(
            name='FieldService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('scheduled', 'برنامه\u200cریزی\u200cشده'), ('in_progress', 'در حال انجام'), ('done', 'انجام\u200cشده')], default='scheduled', max_length=16, verbose_name='وضعیت')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_services', to='workshop.servicerequest', verbose_name='درخواست تعمیر')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_services', to='workshop.technician', verbose_name='تکنسین')),
            ],
            options={
                'verbose_name': 'مأموریت خارج از تعمیرگاه',
                'verbose_name_plural': 'مأموریت\u200cهای خارج از تعمیرگاه',
                'ordering': ['-date'],
            },
        ),
    ]
