# Generated by Django 6.0.6 on 2026-07-05 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_cost', models.DecimalField(decimal_places=0, max_digits=16, verbose_name='برآورد هزینه (ریال)')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='برآورد ساعت کار')),
                ('parts_needed', models.TextField(blank=True, verbose_name='قطعات مورد نیاز (برآوردی)')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات فنی تکنسین')),
                ('status', models.CharField(choices=[('submitted', 'در انتظار تایید مدیر فروش'), ('approved', 'تایید شده (پیش\u200cفاکتور صادر شد)'), ('rejected', 'رد شده')], default='submitted', max_length=16, verbose_name='وضعیت')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_estimates_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط (تکنسین)')),
                ('resulting_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_estimate', to='sales.quote', verbose_name='پیش\u200cفاکتور ساخته\u200cشده')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_estimates_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cشده توسط')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_estimates', to='workshop.servicerequest', verbose_name='درخواست تعمیر')),
            ],
            options={
                'verbose_name': 'برآورد قیمت تعمیر',
                'verbose_name_plural': 'برآوردهای قیمت تعمیر',
                'ordering': ['-created_at'],
            },
        ),
    ]
