# Generated by Django 6.0.6 on 2026-07-06 08:06

import apps.workshop.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_costestimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='customer_feedback',
            field=models.TextField(blank=True, verbose_name='نظر مشتری'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 ستاره'), (2, '2 ستاره'), (3, '3 ستاره'), (4, '4 ستاره'), (5, '5 ستاره')], null=True, verbose_name='امتیاز رضایت مشتری'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت رضایت'),
        ),
        migrations.CreateModel(
            name='ServiceRequestMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.workshop.models.service_request_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'heic', 'mp4', 'mov', 'webm', '3gp'])], verbose_name='فایل (عکس یا فیلم)')),
                ('media_type', models.CharField(blank=True, choices=[('image', 'عکس'), ('video', 'فیلم')], max_length=8, verbose_name='نوع فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_media', to='workshop.servicerequest', verbose_name='درخواست تعمیر')),
            ],
            options={
                'verbose_name': 'رسانه ارسالی مشتری',
                'verbose_name_plural': 'رسانه\u200cهای ارسالی مشتری',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
