# Generated by Django 6.0.6 on 2026-07-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='عکس پروفایل'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیح کوتاه (مثلاً واحد یا تخصص)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ceo', 'مدیرعامل'), ('sales_manager', 'مدیر فروش'), ('sales_rep', 'کارشناس فروش'), ('workshop_manager', 'مدیر تعمیرگاه'), ('technician', 'تکنسین'), ('storekeeper', 'انباردار'), ('accountant', 'حسابداری'), ('customer', 'مشتری (پرتال مشتری)')], default='sales_rep', max_length=32, verbose_name='نقش'),
        ),
    ]
