# Generated by Django 6.0.6 on 2026-07-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'ورود'), ('out', 'خروج')], max_length=8, verbose_name='نوع تراکنش')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('purchase_order_reference', models.CharField(blank=True, max_length=128, verbose_name='ارجاع به سفارش خرید')),
            ],
            options={
                'verbose_name': 'تراکنش انبار',
                'verbose_name_plural': 'تراکنش\u200cهای انبار',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام قطعه')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='کد قطعه')),
                ('brand', models.CharField(blank=True, max_length=128, verbose_name='برند')),
                ('min_stock', models.PositiveIntegerField(default=0, verbose_name='حداقل موجودی')),
                ('max_stock', models.PositiveIntegerField(default=0, verbose_name='حداکثر موجودی')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=16, verbose_name='قیمت واحد (ریال)')),
            ],
            options={
                'verbose_name': 'قطعه',
                'verbose_name_plural': 'قطعات',
                'ordering': ['name'],
            },
        ),
    ]
