# Generated by Django 6.0.6 on 2026-07-04 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='reference_repair_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='workshop.taskassignment', verbose_name='ارجاع به دستورکار تعمیر'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.part', verbose_name='قطعه'),
        ),
    ]
