# Generated by Django 6.0.6 on 2026-07-05 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(verbose_name='تعداد درخواستی')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تامین'), ('fulfilled', 'تامین\u200cشده'), ('rejected', 'رد شده (موجود نیست)')], default='pending', max_length=16, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('fulfilled_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_request', to='inventory.inventorytransaction', verbose_name='تراکنش خروج مرتبط')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='inventory.part', verbose_name='قطعه')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده')),
                ('task_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_requests', to='workshop.taskassignment', verbose_name='مرتبط با دستورکار تعمیر')),
            ],
            options={
                'verbose_name': 'درخواست قطعه',
                'verbose_name_plural': 'درخواست\u200cهای قطعه',
                'ordering': ['-created_at'],
            },
        ),
    ]
